### ISSUE TITLE
Can't hear someone

### ISSUE THREAD

**Issue by tanishqdaiya** [WebDevSimplified/Zoom-Clone-With-WebRTC#38]
I'm facing an issue where I can't hear anyone

**Comment by tanishqdaiya** [comment]
This is not fixed yet,  But, Closing Issue.

**Comment by Dhrumilsoni** [comment]
Any reason as to why this is happening?

I am facing the same issue.

**Comment by liebsen** [comment]
Make sure you're implementing the last versions of peerjs and coturn in case you have installed that, and update your browsers eventually too. 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Dhrumil Soni <notifications@github.com> Date: 20/02/2021  19:30  (GMT-03:00) To: WebDevSimplified/Zoom-Clone-With-WebRTC <Zoom-Clone-With-WebRTC@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [WebDevSimplified/Zoom-Clone-With-WebRTC] Can't hear someone (#38) 

Any reason as to why this is happening?
I am facing the same issue.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/WebDevSimplified/Zoom-Clone-With-WebRTC/issues/38#issuecomment-782759180",
"url": "https://github.com/WebDevSimplified/Zoom-Clone-With-WebRTC/issues/38#issuecomment-782759180",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
